### ISSUE TITLE
Socket error: address already in use

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo#209]
When running AI:MMO locally, as soon as the main page is loaded, the following error appears in the console. It looks like two workers try to connect to the same port. After this error, the game is executed normally.

`Traceback (most recent call last):
  File "service.py", line 44, in <module>
    run(host=sys.argv[1], port=int(sys.argv[2]), directory=sys.argv[3])
  File "service.py", line 41, in run
    app.run(host, port)
  File "/home/ramon/.local/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/ramon/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/home/ramon/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/home/ramon/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/ramon/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
`

**Comment by danalex97** [comment]
I think I fixed the issue, but I will wait for the unity branch to get merged with master before making a pull request.
