### ISSUE TITLE
Unity Branch: Game not starting in unity because of ID issues 

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#237]
So on @ramonfmir's and @danalex97's branch `unity` we came across an issue with @CelineBoudier. Although the game worked fine for me, it did not work for Celine.

We were getting very weird errors that were difficult to trace back. 

```ERROR:simulation.turn_manager:Error while running turn 
Traceback (most recent call last):  
File "/home/celineboudier/code-for-life/worktree/aimmo/aimmo-game/simulation/turn_manager.py", line 91, in run    
   self.end_turn_callback()  
   File "/home/celineboudier/code-for-life/worktree/aimmo/aimmo-game-creator/../aimmo-game/service.py", line 114, in send_world_update    
   def send_world_update(): __send_world_update()  
   File "/home/celineboudier/code-for-life/worktree/aimmo/aimmo-game-creator/../aimmo-game/service.py", line 79, in __send_world_update   
    world_state.get_updates(),  
   File "/home/celineboudier/code-for-life/worktree/aimmo/aimmo-game/simulation/world_state.py", line 38, in get_updates    
   self.refresh()  
   File "/home/celineboudier/code-for-life/worktree/aimmo/aimmo-game/simulation/world_state.py", line 115, in refresh    
   avatar_view = game_state.avatar_manager.get_avatar(main_avatar_id).view  
   File "/home/celineboudier/code-for-life/worktree/aimmo/aimmo-game/simulation/avatar/avatar_manager.py", line 17, in get_avatar    
   return self.avatars_by_id[user_id] 

KeyError: 1
```

The issue was **not** with spacing or tabs in the file.

However, in the `/aimmo-game/simulation/world_state.py` file. There is a comment:

`# TODO: See if any difference between player and avatar id`

There seems to be a difference between the two. The `avatars_by_id` dictionary in `aimmo-game-creator/worker_manager.py` shows:

`{2: Avatar(id=2, location=Location(-2, -1), health=5, score=901)}`

While the `user_id` shows `1`. 

So it's safe to say that they're not the same. Tests are also failing on Celine's laptop.

**Possible reason it worked before:** For some reason our game gets initialized with a player_id and user_id as 1. Celine had an ID of 2, hence it was a KeyError. Is something not being killed correctly?

**Comment by ramonfmir** [comment]
Maybe we left a `user_id = 1` hard-coded somewhere..?

**Comment by OlafSzmidt** [comment]
@ramonfmir Only in `test_service.py` afaik.

**Comment by danalex97** [comment]
Is this a level or generated game?

**Comment by danalex97** [comment]
The fact that the tests fail is interesting. They pass on Travis. The only things that could be different on @CelineBoudier 's laptop(that I can think of) would be the environment and the database.

Another question, does running with Kubernetes work?

**Comment by OlafSzmidt** [comment]
@danalex97 - Yes. We tried removing the db. As for Kubernetes and master, not sure. @CelineBoudier?

**Comment by CelineBoudier** [comment]
@OlafSzmidt @danalex97 On master I have the same error. Running with Kubernetes work with the js grid, not on unity - no specific error, just nothing shows.
