### ISSUE TITLE
Investigate potential kubernetes bug

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#463]
We came across a kubernetes bug trying to get our deploy scripts fully working. The deploy script throws the following traceback:

```
Traceback (most recent call last):
  File "clusters_setup/deploy.py", line 84, in <module>
    main(module_name=sys.argv[1])
  File "clusters_setup/deploy.py", line 70, in main
    kubernetes.config.load_kube_config()
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 361, in load_kube_config
    loader.load_and_set(config)
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 251, in load_and_set
    self._load_authentication()
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 174, in _load_authentication
    if self._load_gcp_token():
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 194, in _load_gcp_token
    self._refresh_gcp_token()
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 203, in _refresh_gcp_token
    credentials = self._get_google_credentials()
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 134, in _refresh_credentials
    credentials.refresh(request)
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 144, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 110, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Empty or missing scope not allowed.', u'{\n  "error" : "invalid_scope",\n  "error_description" : "Empty or missing scope not allowed."\n}')
```

https://github.com/kubernetes-client/python/issues/233

**Comment by OlafSzmidt** [comment]
This has been fixed in https://github.com/kubernetes-client/python-base/pull/40. Ever since there was no stable kubernetes package released so we need to settle down on a pre-release unstable version until one is out. 

I will log this in an issue. For now we will use `5.0.0b1`.
