### ISSUE TITLE
worker_manager cannot obtain game data

### ISSUE THREAD

**Issue by jishi9** [ocadotechnology/aimmo#83]
The worker_manager is unable to hit the endpoint: http://localhost:8000/players/api/games/ ; it gets redirected to the (HTML) login page, resulting in the following error message when attempting to parse the response:

> ERROR:simulation.worker_manager:Obtaining game data failed: No JSON object could be decoded

This happens even if the 'Accept' header is set to 'application/json', so it seems that the `staff_member_required` annotation does not respect the 'Accept' header.

**Comment by Spycho** [comment]
Ah, that will be my change to lock down the ui so we can deploy it, sorry. I'll remove the restriction on that - we don't really mind if people can read game data.

**Comment by Spycho** [comment]
I think I've removed the restriction from all that we need (0532ec00b20de6dded8d371a79cae7d9ccc311fb), but can't test it locally because of the following (I think because of Windows):

DEBUG:requests.packages.urllib3.connectionpool:"GET /players/api/games/ HTTP/1.1" 200 None
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\c.brett\Workspaces\aimmo\aimmo-game\simulation\worker_manager.py", line 52, in run
    user['id'],
  File "C:\Users\c.brett\Workspaces\aimmo\aimmo-game\simulation\worker_manager.py", line 92, in create_worker
    str(self.next_port),
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by jishi9** [comment]
Works for me, thanks 👍
